# Date of import
cbnmc_import_date="2026-06-13"
# Data to import filename prefix
cbnmc_filename_prefix="${cbnmc_import_date}_sinp_aura_cbnmc"
# Archive data filename to import (need to be ".csv" files into a ".tar.bz2" archive file)
cbnmc_filename_archive="${cbnmc_filename_prefix}.tar.bz2"
