# GN2PG configuration file

# Local db configuration
[db]
db_host = "localhost"
db_port = 5432
db_user = "geonatadmin"
db_password = "<mot-de-passe>"
db_name = "geonature2db"
db_schema_import = "gn2pg_import"
    # Additional connection options (optional)
    #[db.db_querystring]
    #sslmode = "prefer"


# Source configuration,
# Ducplicate this block for each source (1 source = 1 export)
[[source]]
# Source name, will be use to tag stored data in import table
name = "LPO"
# GeoNature source login
user_name = "jpmilcent"
# GeoNature source password
user_password = "<mot-de-passe>"
# GeoNature source URL
url = "https://orb.lpo-aura.org/"
# GeoNature source Export id
export_id = 2
# Data type (used to distinct datas and to conditionning triggers)
#data_type = "synthese_with_cd_nomenclature"
data_type = "synthese_with_metadata"
# GeoNature ID application (default is 3)
id_application = 1
# Enable source
enable = true
# Additional export API QueryStrings to filter or order data, you can add multiple "orderby" columns by separating column names with ":"
[source.query_strings]
orderby = 'id_synthese'


[tuning]
# Max items in an API list request.
# Longer lists are split by API in max_list_length chunks.
max_page_length = 10000
# Max retries of API calls before aborting.
max_retry = 5
# Maximum number of API requests, for debugging only.
# - 0 means unlimited
# - >0 limit number of API requests
max_requests = 0
# Delay between retries after an error
retry_delay = 5
# Delay between retries after an error HTTP 503 (service unavailable)
unavailable_delay = 600
# LRU cache size for common requests (taxo_groups...)
lru_maxsize = 64
